# Generated by Django 3.2.16 on 2024-12-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Неопределенный тип', max_length=128, verbose_name='Тип оборудования')),
                ('img_path', models.ImageField(default='no_image.png', upload_to='equipments/', verbose_name='Путь до изображения')),
                ('installed_apps_and_games', models.TextField(null=True, verbose_name='Установленные игры и приложения')),
                ('serviceability', models.BooleanField(default=True, verbose_name='Признак готовности к работе')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('weekday', models.BooleanField(default=True, verbose_name='Будний день')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена услуги за час')),
            ],
        ),
    ]
